modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="netherenditions"
version="0.1.1"
displayName="Netherenditions Revived"
displayURL="https://modrinth.com/mod/netherenditions"
credits="END"
authors="ErzeKawek, Woorlay"
description="A Reborn and Hard Fork Of Netherenditions for Forge."

[[dependencies.netherenditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




