modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="areas_undiscovered"
version="1.0.24"
displayName="Areas Undiscovered"
displayURL="https://modrinth.com/project/areas-undiscovered"
logoFile="logo.png"
credits="Hey"
authors="ErzeKawek, Woorlay, C418, & Bottetoundra719"
description="Discover the Undiscovered Areas!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.areas_undiscovered]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



